# Generated by Django 5.1.7 on 2025-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_class_year_subject_year_subject_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='9818b2098a24477cbd0bd09a8aa98c07', max_length=64, unique=True),
        ),
    ]
