# Generated by Django 5.1.7 on 2025-04-16 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendancesession_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='qr_code_data',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='303f8b39e7cf46cfad79cd0d4fedd8d9', max_length=64, unique=True),
        ),
    ]
