# Generated by Django 5.1.7 on 2025-04-16 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_attendancesession_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='class_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classyear'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='21b7059fb19042d9ac6c0c719fa8e491', max_length=64, unique=True),
        ),
    ]
