# Generated by Django 5.1.7 on 2025-04-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendancesession_class_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='400e392ef65c4147befbef2e19396e23', max_length=64, unique=True),
        ),
    ]
