# Generated by Django 5.1.7 on 2025-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='18304ed2fbce40c6bbc20e6839577359', max_length=64, unique=True),
        ),
    ]
