# Generated by Django 5.1.7 on 2025-04-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attendancesession_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='f2831980180c4937bef724123c9f5bba', max_length=64, unique=True),
        ),
    ]
