# Generated by Django 5.1.7 on 2025-04-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='b2c3fb6aa7e74dc5838635fd05cd956b', max_length=64, unique=True),
        ),
    ]
