# Generated by Django 5.1.7 on 2025-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='1e7ae898b29d4c56a87fd4918bf901ae', max_length=64, unique=True),
        ),
    ]
