# Generated by Django 5.1.7 on 2025-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='762ee22d820b4c7caa835bf36f88a269', max_length=64, unique=True),
        ),
    ]
