# Generated by Django 5.1.7 on 2025-04-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='4963b24fe60b478abfd5c0f6ea73154a', max_length=64, unique=True),
        ),
    ]
