# Generated by Django 5.1.7 on 2025-04-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='043faa3d65e7453e88c40c89c106e641', max_length=64, unique=True),
        ),
    ]
