# Generated by Django 5.1.7 on 2025-04-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='98914c7a892542ed8dfabfc26f59d25f', max_length=64, unique=True),
        ),
    ]
