# Generated by Django 5.1.7 on 2025-04-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='7e2a4e5b5a234e6ebb273903a8d5895f', max_length=64, unique=True),
        ),
    ]
