# Generated by Django 5.1.7 on 2025-04-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_attendancesession_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='13b372a838494baeac0935650f0aed3d', max_length=64, unique=True),
        ),
    ]
