# Generated by Django 5.1.7 on 2025-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_attendancesession_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='54033d478fdb4b37955f397c4b5ef24c', max_length=64, unique=True),
        ),
    ]
