# Generated by Django 5.1.7 on 2025-04-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_attendancesession_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='cc3ad534ef5a43f3ac4d1d252bfd6229', max_length=64, unique=True),
        ),
    ]
