# Generated by Django 5.1.7 on 2025-04-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_attendancerecord_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='9c949ba599d243e0a8e78295c1596d9b', max_length=64, unique=True),
        ),
    ]
