# Generated by Django 5.1.7 on 2025-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='token',
            field=models.CharField(default='59901ea3aa5b438cad47ea5f27b98573', max_length=64, unique=True),
        ),
    ]
