# Generated by Django 5.1.7 on 2025-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_attendancesession_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='roll_number',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
