# Generated by Django 5.1.7 on 2025-04-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_attendancerecord_roll_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'session')},
        ),
    ]
