# Generated by Django 5.1.7 on 2025-04-24 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_attendancerecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 24)),
        ),
    ]
