# Generated by Django 5.1.7 on 2025-04-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_attendancesession_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(),
        ),
    ]
