# Generated by Django 5.1.7 on 2025-04-24 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
