"""
Django settings for attendance_system project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g!t(fh3w3r*z@n0zop)+cx6c*a&6de^yv9lx4w!4)d3cp09bo6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'attendance_system.urls'

import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attendance_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
        # 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
        # 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
        # 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
        # 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

TIME_ZONE = 'Asia/Kolkata'  # or any other timezone you need
USE_TZ = True

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.ngrok.io', 'fda8-2409-40c0-100c-ce07-591e-264d-121b-e73d.ngrok-free.app', '21a7-2409-40c0-103d-c370-f4c9-4577-5200-9733.ngrok-free.app']
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    # 'https://21a7-2409-40c0-103d-c370-f4c9-4577-5200-9733.ngrok-free.app',
    # 'http://21a7-2409-40c0-103d-c370-f4c9-4577-5200-9733.ngrok-free.app',
    # 'https://18e1-2409-40c0-103d-c370-f4c9-4577-5200-9733.ngrok-free.app',
    # 'https://f332-2409-40c0-103d-c370-f4c9-4577-5200-9733.ngrok-free.app',
    # 'https://7f62-2409-40c0-103d-c370-f4c9-4577-5200-9733.ngrok-free.app',
    # 'https://8895-2409-40c2-7000-f06a-f8dc-2cdf-7933-7a1d.ngrok-free.app',
    # 'https://bc42-2409-40c2-7000-f06a-f8dc-2cdf-7933-7a1d.ngrok-free.app',
    # 'https://bc42-2409-40c2-7000-f06a-f8dc-2cdf-7933-7a1d.ngrok-free.app',
    # 'https://9fd6-2409-40c2-103e-4815-c496-50c0-7459-4bd2.ngrok-free.app',
    # 'https://9de5-2409-40c0-1e-38bc-a536-4a2-f61c-7653.ngrok-free.app',
    # 'https://8649-2409-40c0-1055-336b-599e-d5c4-fcee-d984.ngrok-free.app',
    # 'https://07e3-2409-40c0-70-2eef-75ba-99cd-468-4bb4.ngrok-free.app',
    # 'https://593a-2409-40c0-70-2eef-75ba-99cd-468-4bb4.ngrok-free.app',
    # 'https://83d5-2409-40c0-70-2eef-75ba-99cd-468-4bb4.ngrok-free.app',
    # 'https://4b1c-2409-40c0-70-2eef-75ba-99cd-468-4bb4.ngrok-free.app',
    # 'https://7b85-2409-40c0-70-2eef-75ba-99cd-468-4bb4.ngrok-free.app',
    # 'https://57db-2409-40c0-70-2eef-75ba-99cd-468-4bb4.ngrok-free.app',
    # 'https://c931-2409-40c2-7056-e475-8833-7596-74b0-a8ca.ngrok-free.app',
    'https://4719-152-56-8-184.ngrok-free.app',
    'https://11e6-2409-40c2-116e-402b-bd1f-6d53-a57f-49f4.ngrok-free.app',
    'https://cf0b-103-87-28-27.ngrok-free.app',
]


